facebook:
  verify: "hakunamatata"
  secret: "a49dde4b386e3101b3ceb17ac3618bfd"
  page-access-token: "EAAGAvDnZCgV4BALiUIjVvhYUGKYLjZBlIZCJOovPoxCNTSm4HX3EeQcllIsG5eYlHp5ovf7Q1ZAti3EofYGURZCj4rXCO0W3LpdIVc4JQXjQgRjwnGteaTVl0wziy4OWcoXJ5sZCY6IdWy2EVeGGKU058yfsbIB0SZBwF5gwhIZBEwZDZD"
socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true


#rasa: 
#  url: "http://localhost:3000/api"